// Public Books
export const PUBLIC_BOOKS_REQUEST = 'PUBLIC_BOOKS_REQUEST ';
export const PUBLIC_BOOKS_SUCCESS = 'PUBLIC_BOOKS_SUCCESS';
export const PUBLIC_BOOKS_FAIL = 'PUBLIC_BOOKS_FAIL';

// Public Books Details Page
export const BOOK_DETAIL_REQUEST = 'BOOK_DETAIL_REQUEST ';
export const BOOK_DETAIL_SUCCESS = 'BOOK_DETAIL_SUCCESS';
export const BOOK_DETAIL_FAIL = 'BOOK_DETAIL_FAIL';